# Generated by Django 4.2.4 on 2023-08-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='host_request_status',
            field=models.CharField(default='', max_length=15),
        ),
    ]
