# Generated by Django 4.2.4 on 2023-08-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email_user_first_name_user_last_name_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='tenant', max_length=25),
        ),
    ]
