# Generated by Django 4.2.4 on 2023-09-29 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_listing_bathrooms_alter_listing_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='reviews',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='listing',
            name='payment',
            field=models.CharField(default='month', max_length=25),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(max_length=25),
        ),
    ]
